// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: proto/fund_transfer.proto

package fundtransfer

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FundTransferService_ProcessFundTransfer_FullMethodName = "/fundtransfer.FundTransferService/ProcessFundTransfer"
)

// FundTransferServiceClient is the client API for FundTransferService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FundTransferServiceClient interface {
	// RPC for processing fund transfers
	ProcessFundTransfer(ctx context.Context, in *TransferRequest, opts ...grpc.CallOption) (*TransferResponse, error)
}

type fundTransferServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFundTransferServiceClient(cc grpc.ClientConnInterface) FundTransferServiceClient {
	return &fundTransferServiceClient{cc}
}

func (c *fundTransferServiceClient) ProcessFundTransfer(ctx context.Context, in *TransferRequest, opts ...grpc.CallOption) (*TransferResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TransferResponse)
	err := c.cc.Invoke(ctx, FundTransferService_ProcessFundTransfer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FundTransferServiceServer is the server API for FundTransferService service.
// All implementations must embed UnimplementedFundTransferServiceServer
// for forward compatibility.
type FundTransferServiceServer interface {
	// RPC for processing fund transfers
	ProcessFundTransfer(context.Context, *TransferRequest) (*TransferResponse, error)
	mustEmbedUnimplementedFundTransferServiceServer()
}

// UnimplementedFundTransferServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFundTransferServiceServer struct{}

func (UnimplementedFundTransferServiceServer) ProcessFundTransfer(context.Context, *TransferRequest) (*TransferResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProcessFundTransfer not implemented")
}
func (UnimplementedFundTransferServiceServer) mustEmbedUnimplementedFundTransferServiceServer() {}
func (UnimplementedFundTransferServiceServer) testEmbeddedByValue()                             {}

// UnsafeFundTransferServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FundTransferServiceServer will
// result in compilation errors.
type UnsafeFundTransferServiceServer interface {
	mustEmbedUnimplementedFundTransferServiceServer()
}

func RegisterFundTransferServiceServer(s grpc.ServiceRegistrar, srv FundTransferServiceServer) {
	// If the following call pancis, it indicates UnimplementedFundTransferServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FundTransferService_ServiceDesc, srv)
}

func _FundTransferService_ProcessFundTransfer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TransferRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FundTransferServiceServer).ProcessFundTransfer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FundTransferService_ProcessFundTransfer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FundTransferServiceServer).ProcessFundTransfer(ctx, req.(*TransferRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FundTransferService_ServiceDesc is the grpc.ServiceDesc for FundTransferService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FundTransferService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "fundtransfer.FundTransferService",
	HandlerType: (*FundTransferServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ProcessFundTransfer",
			Handler:    _FundTransferService_ProcessFundTransfer_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/fund_transfer.proto",
}
